### PR TITLE
fixing a bug

### PR DESCRIPTION
**Pull request by matthieu80**
I kept getting the error:
`'scope': You tried to define a scope named "name" on the model "Space", but Active Record already defined a class method with the same name. (ArgumentError)`
so I changed the name of the filter with a prefix 'filter_'

Also I added a URI.decode on the value which I think is necessary

### CODE REVIEW

**Comment by guillaumebriday** [comment]
Hey @matthieu80 

Could you give me more details on your model `Space` please ? Do you have any `delegate` or instance method using `name` ?

I think it's a good idea to add `URI.decode`

Thank you

**Comment by matthieu80** [comment]
Salut @guillaumebriday  
I believe Class has a name method in ruby, thus the error. It could happen with any other methods already present on Class, on Object etc.... I think 'namespacing' the scope with 'filter' or even 'jsonapi-scope' makes sense.

**Comment by guillaumebriday** [comment]
Hum ok I'll take a look today ! Thanks

**Comment by guillaumebriday** [comment]
Hey !

You're right, we cannot use `name` for named scope, but it's a rails limitation and `filter` is basically a wrapper around native scope.

I want this gem to be very simple and straightforward, so if you cannot do it with rails, we shouldn't be able to do it with this gem 😛 Just change you scope's name by `by_name` for example.

Same for `URI.decode`, you can decode params before call `apply_filter` if you want/need.

Thank you for the PR.

ps: I added some tests (https://github.com/guillaumebriday/jsonapi-scopes/commit/5efd8e3b4bf64833fd863406f45139863055aeb0)

**Pull request closed without merging**
